import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";

export const metadata = {
  title: "Hero KidZ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {/* Navbar */}
        <Navbar />

        {/* main */}
        <main className="min-h-[calc(100vh-81px-275px)]">{children}</main>

        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
