import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {/* Navbar */}
        <Navbar/>

        {/* main */}
        <main>{children}</main>

        {/* Footer */}
        <footer></footer>
      </body>
    </html>
  );
}
